window.PORTFOLIO = {
  githubProfile: "https://github.com/Saban2412",
  cv: "downloads/Emir_Sabanovic_Resume.pdf",
  projects: {
    en: {
      "project-1": {
        title: "CRUD API",
        tech: "NODE.JS / POSTGRESQL / DOCKER",
        desc: "A production-ready RESTful API built with robust data modeling and relational integrity. Features containerized deployment for seamless scalability and consistent environments across dev and production.",
        dev: "Architecture focuses on layered separation of concerns (Controllers, Services, Repositories). Optimized connection pooling for PostgreSQL and comprehensive integration tests wrapped inside Docker environments.",
        images: ["images/mockup-taskapi.png"],
        repo: "https://github.com/Saban2412",
      },
      "project-2": {
        title: "Polite Scraper",
        tech: "NODE.JS / ZOD",
        desc: "A highly efficient web scraping utility engineered with strict rate-limiting and robust data validation routines. Designed to respect target server guidelines while ensuring type-safe extraction of complex web structures.",
        dev: "Built using asynchronous queues to prevent IP throttling. Implements Zod schemas at the edge to instantly validate incoming HTML-parsed payloads, converting unstructured web data into strictly-typed JSON.",
        images: ["images/scraper.png"],
        repo: "https://github.com/Saban2412",
      },
      "project-3": {
        title: "AUTH System",
        tech: "NODE.JS / SUPABASE / POSTGRESQL",
        desc: "A secure, production-grade authentication and authorization gateway integrated with a modern headless backend. Fully documented with interactive API specifications for seamless frontend and third-party consumption.",
        dev: "Features JWT-based access controls and secure refresh token rotations. Integrated with Supabase Auth for backend storage, while completely mapped through Swagger UI, allowing backend-driven route exploration.",
        images: ["images/Screenshot 2026-08-29 084623.png"],
        repo: "https://github.com/Saban2412",
      },
    },
    bs: {
      "project-1": {
        title: "CRUD API",
        tech: "NODE.JS / POSTGRESQL / DOCKER",
        desc: "RESTful API izgrađen uz stabilno modeliranje podataka i relacioni integritet. Kontejneriziran za dosljedna okruženja u razvoju i produkciji.",
        dev: "Arhitektura je podijeljena po slojevima (Controllers, Services, Repositories). Connection pooling za PostgreSQL i integracijski testovi unutar Docker okruženja.",
        images: ["images/mockup-taskapi.png"],
        repo: "https://github.com/Saban2412",
      },
      "project-2": {
        title: "Polite Scraper",
        tech: "NODE.JS / ZOD",
        desc: "Visoko efikasan alat za web scraping, projektovan sa strogim ograničenjem brzine i stabilnim rutinama za validaciju podataka.",
        dev: "Asinhroni redovi sprečavaju throttling. Zod šeme validiraju parsiran HTML i pretvaraju nestrukturirane podatke u strogo tipizirani JSON.",
        images: ["images/scraper.png"],
        repo: "https://github.com/Saban2412",
      },
      "project-3": {
        title: "AUTH Sistem",
        tech: "NODE.JS / SUPABASE / POSTGRESQL",
        desc: "Siguran autentifikacijski i autorizacijski gateway spreman za produkciju, integrisan sa modernim headless backendom.",
        dev: "JWT pristup i rotacija refresh tokena. Supabase Auth za pohranu, rute dokumentovane kroz Swagger UI.",
        images: ["images/Screenshot 2026-08-29 084623.png"],
        repo: "https://github.com/Saban2412",
      },
    },
  },
  certs: {
    en: {
      "cert-1": {
        title: "Claude Platform 101",
        category: "CLAUDE / AI AGENTS / MCP SERVERS",
        date: "June 2026",
        issuer: "Anthropic",
        desc: "Certificate of completion for an advanced course on AI agent development and MCP server implementation.",
        image: "images/claude_platform_101.jpg",
        link: "https://verify.skilljar.com/c/ayez7wk85qsy",
      },
      "cert-2": {
        title: "Claude 101",
        category: "CLAUDE / AI",
        date: "July 2026",
        issuer: "Anthropic",
        desc: "Foundations of working with Claude across prompting, workflows, and practical AI-assisted development.",
        image: "images/CLAUDE_101.jpg",
        link: "https://verify.skilljar.com/c/zh7jafh58994",
      },
      "cert-3": {
        title: "AI Fluency: Framework & Foundations",
        category: "CLAUDE / AI FLUENCY",
        date: "July 2025",
        issuer: "Anthropic",
        desc: "Framework for using AI as a thinking partner in real engineering work, not as a shortcut.",
        image: "images/AI_FLUENCY_CERT.jpg",
        link: "https://verify.skilljar.com/c/jemkq975yk89",
      },
      "cert-4": {
        title: "Introduction to Claude Cowork",
        category: "CLAUDE COWORK / AI",
        date: "August 2025",
        issuer: "Anthropic",
        desc: "Working with Claude Cowork for collaborative, agent-style development workflows.",
        image: "images/Cowork_cert_page-0001.jpg",
        link: "https://verify.skilljar.com/c/ndoduyqjoydc",
      },
      "cert-5": {
        title: "Google Cloud Digital Leader",
        category: "GOOGLE / CLOUD",
        date: "August 2025",
        issuer: "Google Cloud",
        desc: "Fundamentals of cloud infrastructure, services, and security within the Google Cloud platform.",
        image: "",
        link: "",
      },
      "cert-6": {
        title: "Meta Backend Developer",
        category: "META / BACKEND",
        date: "June 2025",
        issuer: "Meta",
        desc: "Server-side development, API design, and security fundamentals for backend applications.",
        image: "",
        link: "",
      },
      "cert-7": {
        title: "APIs and Microservices",
        category: "JAVASCRIPT / API",
        date: "April 2025",
        issuer: "freeCodeCamp",
        desc: "Building and testing REST APIs and microservices with Node.js and Express.",
        image: "",
        link: "",
      },
      "cert-8": {
        title: "Postman API Fundamentals",
        category: "API / TESTING",
        date: "February 2025",
        issuer: "Postman",
        desc: "Testing, documenting, and automating API requests through Postman collections.",
        image: "",
        link: "",
      },
      "cert-9": {
        title: "GitHub Foundations",
        category: "GIT / VERSION CONTROL",
        date: "December 2024",
        issuer: "GitHub",
        desc: "Version control, branching, and project collaboration fundamentals with GitHub.",
        image: "",
        link: "",
      },
    },
    bs: {
      "cert-1": {
        title: "Claude Platform 101",
        category: "CLAUDE / AI AGENTS / MCP SERVERS",
        date: "Juni 2026",
        issuer: "Anthropic",
        desc: "Sertifikat o završenom kursu razvoja AI agenata i implementacije MCP servera.",
        image: "images/claude_platform_101.jpg",
        link: "https://verify.skilljar.com/c/ayez7wk85qsy",
      },
      "cert-2": {
        title: "Claude 101",
        category: "CLAUDE / AI",
        date: "Juli 2026",
        issuer: "Anthropic",
        desc: "Osnove rada s Claudeom: prompting, tokovi rada i praktičan razvoj uz AI.",
        image: "images/CLAUDE_101.jpg",
        link: "https://verify.skilljar.com/c/zh7jafh58994",
      },
      "cert-3": {
        title: "AI Fluency: Framework & Foundations",
        category: "CLAUDE / AI FLUENCY",
        date: "Juli 2025",
        issuer: "Anthropic",
        desc: "Okvir za korištenje AI-a kao partnera za razmišljanje u inženjerskom radu, ne kao prečice.",
        image: "images/AI_FLUENCY_CERT.jpg",
        link: "https://verify.skilljar.com/c/jemkq975yk89",
      },
      "cert-4": {
        title: "Introduction to Claude Cowork",
        category: "CLAUDE COWORK / AI",
        date: "August 2025",
        issuer: "Anthropic",
        desc: "Rad s Claude Cowork za kolaborativne, agentske tokove razvoja.",
        image: "images/Cowork_cert_page-0001.jpg",
        link: "https://verify.skilljar.com/c/ndoduyqjoydc",
      },
      "cert-5": {
        title: "Google Cloud Digital Leader",
        category: "GOOGLE / CLOUD",
        date: "August 2025",
        issuer: "Google Cloud",
        desc: "Osnove cloud infrastrukture, usluga i sigurnosti unutar Google Cloud platforme.",
        image: "",
        link: "",
      },
      "cert-6": {
        title: "Meta Backend Developer",
        category: "META / BACKEND",
        date: "Juni 2025",
        issuer: "Meta",
        desc: "Server-side razvoj, API dizajn i osnove sigurnosti backend aplikacija.",
        image: "",
        link: "",
      },
      "cert-7": {
        title: "APIs and Microservices",
        category: "JAVASCRIPT / API",
        date: "April 2025",
        issuer: "freeCodeCamp",
        desc: "Izrada i testiranje REST API-ja i mikroservisa u Node.js/Express okruženju.",
        image: "",
        link: "",
      },
      "cert-8": {
        title: "Postman API Fundamentals",
        category: "API / TESTING",
        date: "Februar 2025",
        issuer: "Postman",
        desc: "Testiranje, dokumentovanje i automatizacija API poziva kroz Postman kolekcije.",
        image: "",
        link: "",
      },
      "cert-9": {
        title: "GitHub Foundations",
        category: "GIT / VERSION CONTROL",
        date: "Decembar 2024",
        issuer: "GitHub",
        desc: "Osnove verzionisanja koda, grananja i saradnje na projektima kroz GitHub.",
        image: "",
        link: "",
      },
    },
  },
};
